version: "3.1"
services:
    mariadb:
      image: mariadb:latest
      volumes:
        - ./docker/mariadb/entrypoint:/docker-entrypoint-initdb.d
        - mariadb:/var/lib/mysql
      environment:
        #- MARIADB_ROOT_PASSWORD_HASH=*E56A114692FE0DE073F9A1DD68A00EEB9703F3F1
        - MARIADB_ROOT_PASSWORD=sup3rs3cr3t
        - MARIADB_DATABASE=devops_lab01
        - MARIADB_USER=devops
        - MARIADB_PASSWORD=123123
      ports:
        - 3316:3306
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

    nginx:
      image: nginx:latest
      depends_on: [mariadb]
      volumes:
        - ./docker/nginx/web:/usr/share/nginx/html
      ports:
        - 8080:80
volumes:
  mariadb:
